from pathlib import Path

path = Path('static/src/App.tsx')
text = path.read_text()

# Make validation orchestration-aware: orchestration migrations intentionally do not
# require project-level screen/workflow-scheme mutations.
old = """    const automation = automationMigrationPack(service);\n    const workflowSource = service.analysis.workflowItems.length > 0;\n    const portalDone = !!portal?.visibleInPortal || !!manualPortalComplete[service.id];\n    const items = [\n"""
new = """    const automation = automationMigrationPack(service);\n    const workflowSource = service.analysis.workflowItems.length > 0;\n    const orchestrationSource = (service.analysis.workflowItems ?? []).some((item) => /all\\s*tasks?\\s*complete|servicedesk|source defect|active directory|office 365|harvest|assets|pbx/i.test(String(item.label ?? '')));\n    const portalDone = !!portal?.visibleInPortal || !!manualPortalComplete[service.id];\n    const items = [\n"""
if old not in text:
    raise SystemExit('validation preamble not found')
text = text.replace(old, new, 1)

old_screen = """      { key:'screens', label:'Screens & schemes', status: screens?.status === 'created' && !!screenActivation ? 'pass' : screens?.status === 'failed' ? 'fail' : 'warning', source:'Required', jira: screens ? screens.status : 'Not run', message: screenActivation ? 'Screen structure is built and assigned to the target project.' : screens ? 'Screen structure exists; project assignment still needs verification.' : 'Screen build has not been run in this session.' },\n"""
new_screen = """      { key:'screens', label:'Screens & schemes', status: orchestrationSource ? 'pass' : screens?.status === 'created' && !!screenActivation ? 'pass' : screens?.status === 'failed' ? 'fail' : 'warning', source:orchestrationSource ? 'Not required' : 'Required', jira: orchestrationSource ? 'Protected orchestration path' : screens ? screens.status : 'Not run', message: orchestrationSource ? 'No project-level screen or workflow-scheme mutation is required for this orchestration migration.' : screenActivation ? 'Screen structure is built and assigned to the target project.' : screens ? 'Screen structure exists; project assignment still needs verification.' : 'Screen build has not been run in this session.' },\n"""
if old_screen not in text:
    raise SystemExit('screen validation row not found')
text = text.replace(old_screen, new_screen, 1)

# Add reusable cutover classification and CSV export.
marker = """  function exportValidationReport(service: MigrationService) {\n"""
insert = """  function cutoverFor(service: MigrationService) {\n    const validation = validationFor(service);\n    const signoff = validationSignoff[service.id] || 'not-tested';\n    const hasBuildEvidence = service.build.fieldResults.some((result) => ['created','reused','partial'].includes(result.status)) || !!jsmRequestResults[service.id] || !!jsmFormResults[service.id];\n    const sourceDefects = (service.analysis.workflowItems ?? []).filter((item) => /source defect/i.test(String(item.label ?? ''))).length;\n    let status: 'Ready to cut over' | 'Needs review' | 'Blocked' | 'Not migrated';\n    let reason: string;\n    if (!hasBuildEvidence) { status = 'Not migrated'; reason = 'No Jira build evidence is recorded for this service yet.'; }\n    else if (validation.failures > 0 || validation.blockers > 0) { status = 'Blocked'; reason = `${validation.failures} validation failure(s), ${validation.blockers} blocker(s).`; }\n    else if (validation.warnings > 0 || !['passed','approved'].includes(signoff) || sourceDefects > 0) {\n      status = 'Needs review';\n      const parts = [];\n      if (validation.warnings) parts.push(`${validation.warnings} warning/manual step(s)`);\n      if (!['passed','approved'].includes(signoff)) parts.push('end-to-end sign-off outstanding');\n      if (sourceDefects) parts.push(`${sourceDefects} source defect(s) quarantined`);\n      reason = parts.join(' · ');\n    } else { status = 'Ready to cut over'; reason = 'Automated validation and runtime sign-off are complete.'; }\n    return { status, reason, validation, signoff, sourceDefects };\n  }\n\n  function exportCutoverReadinessCsv() {\n    const rows = [['Service','Status','Validation score','Failures','Blockers','Warnings','Runtime sign-off','Source defects','Reason','Source file']];\n    migration.services.forEach((service) => {\n      const cutover = cutoverFor(service);\n      rows.push([\n        service.analysis.serviceName, cutover.status, String(cutover.validation.score), String(cutover.validation.failures),\n        String(cutover.validation.blockers), String(cutover.validation.warnings), cutover.signoff, String(cutover.sourceDefects),\n        cutover.reason, service.sourceFile\n      ]);\n    });\n    exportCsv('ivanti-jira-cutover-readiness.csv', rows);\n  }\n\n"""
if marker not in text:
    raise SystemExit('validation export marker not found')
text = text.replace(marker, insert + marker, 1)

old_report = """        {mainView === 'report' && (\n          <section className=\"panel fullPanel\">\n            <div className=\"row\"><div><h1>Migration report</h1><p className=\"hint\">A management-friendly summary of migration progress and outstanding review work.</p></div><div className=\"actions\"><button className=\"secondary\" onClick={exportFieldMappingCsv}>Export field mapping CSV</button><button className=\"secondary\" onClick={exportImplementationChecklistCsv}>Export checklist CSV</button></div></div>\n            <div className=\"reportMetrics\">\n              <div><strong>{migration.services.length}</strong><span>Services imported</span></div>\n              <div><strong>{overall.totalFields}</strong><span>Field references</span></div>\n              <div><strong>{sharedFields.length}</strong><span>Unique Jira fields</span></div>\n              <div><strong>{overall.created}</strong><span>Fields created/reused</span></div>\n              <div><strong>{overall.review}</strong><span>Workflows needing review</span></div>\n            </div>\n            <div className=\"reportList\">\n              {migration.services.map((service) => <article key={service.id}><div><strong>{service.analysis.serviceName}</strong><p>{service.analysis.fields.length} fields · {service.formSections.length} sections · {automationBlueprint(service).length} automation rules</p></div><span>{serviceReadiness(service)}%</span></article>)}\n            </div>\n          </section>\n        )}\n"""

new_report = """        {mainView === 'report' && (\n          <section className=\"panel fullPanel\">\n            <div className=\"row\"><div><p className=\"eyebrow dark\">Ivanti shutdown assurance</p><h1>Cutover readiness</h1><p className=\"hint\">Estate-level status for every imported Ivanti service. A service only reaches Ready to cut over after validation and runtime sign-off.</p></div><div className=\"actions\"><button className=\"secondary\" onClick={exportCutoverReadinessCsv}>Export cutover CSV</button><button className=\"secondary\" onClick={exportFieldMappingCsv}>Export field mapping CSV</button><button className=\"secondary\" onClick={exportImplementationChecklistCsv}>Export checklist CSV</button></div></div>\n            <div className=\"reportMetrics\">\n              <div><strong>{migration.services.length}</strong><span>Services discovered</span></div>\n              <div><strong>{migration.services.filter(s=>cutoverFor(s).status==='Ready to cut over').length}</strong><span>Ready to cut over</span></div>\n              <div><strong>{migration.services.filter(s=>cutoverFor(s).status==='Needs review').length}</strong><span>Needs review</span></div>\n              <div><strong>{migration.services.filter(s=>cutoverFor(s).status==='Blocked').length}</strong><span>Blocked</span></div>\n              <div><strong>{migration.services.filter(s=>cutoverFor(s).status==='Not migrated').length}</strong><span>Not migrated</span></div>\n            </div>\n            <div className=\"reportList\">\n              {migration.services.map((service) => { const c=cutoverFor(service); return <article key={service.id}><div><strong>{service.analysis.serviceName}</strong><p>{c.reason}</p><small>{service.analysis.fields.length} fields · {service.formSections.length} sections · {service.analysis.workflowItems.length} workflow items · {c.validation.score}% validation</small></div><div className=\"validationServiceActions\"><span className={`comparisonStatus ${c.status==='Ready to cut over'?'reuse':c.status==='Blocked'?'review':c.status==='Not migrated'?'new':'review'}`}>{c.status}</span><button className=\"secondary\" onClick={()=>{setActiveServiceId(service.id);setMainView('services');setServiceView('validation')}}>Open validation</button></div></article> })}\n            </div>\n            {!migration.services.length && <div className=\"emptyState\"><strong>No Ivanti services imported</strong><p>Bulk-import the Request Offering exports to build the estate cutover view.</p></div>}\n          </section>\n        )}\n"""
if old_report not in text:
    raise SystemExit('migration report block not found')
text = text.replace(old_report, new_report, 1)

path.write_text(text)
print('Applied estate cutover readiness patch')
