import api, { route } from '@forge/api';
import { kvs } from '@forge/kvs';

export type GraphNodeKind = 'start'|'stop'|'task'|'gate'|'decision'|'action'|'wait'|'approval'|'unsupported';
export type GraphNode = { id:string; sourceType:string; kind:GraphNodeKind; title:string; summary?:string; details?:string; team?:string; dueDays?:number; actionKind?:string; condition?:string; outcomes:string[] };
export type GraphTransition = { sourceId:string; sourceTitle:string; outcome:string; condition?:string; targetId:string; targetTitle:string };
export type ExecutableGraphPlan = { version:2; serviceId:string; serviceName:string; projectId:string; issueTypeId:string; workflowName:string; workflowVersion:string; entryNodeIds:string[]; nodes:GraphNode[]; transitions:GraphTransition[]; defects?:string[]; installedAt?:string };
type State={parentIssueId:string;parentIssueKey:string;createdTasks:Record<string,string>;active:string[];passed:string[];completed:boolean;updatedAt:string};
type Issue={id:string;key:string;fields?:Record<string,any>&{project?:{id?:string};issuetype?:{id?:string;subtask?:boolean};parent?:{id?:string;key?:string};status?:{name?:string;statusCategory?:{key?:string}};created?:string;labels?:string[]}};
const PLAN='ivanti-executable-graph-v2'; const STATE='ivanti-graph-state-v2'; const clean=(v:unknown)=>String(v??'').replace(/\s+/g,' ').trim(); const norm=(v:unknown)=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const planKey=(p:string,t:string)=>`${PLAN}:${p}:${t}`; const stateKey=(id:string)=>`${STATE}:${id}`;
async function json<T>(r:any):Promise<T>{const text=await r.text();let body:any;try{body=text?JSON.parse(text):undefined}catch{body=text}if(!r.ok)throw new Error(`Jira ${r.status}: ${typeof body==='string'?body.slice(0,400):JSON.stringify(body).slice(0,400)}`);return body as T}
async function issue(key:string):Promise<Issue>{return json(await api.asApp().requestJira(route`/rest/api/3/issue/${key}?fields=project,issuetype,parent,status,created,labels,*all`,{headers:{Accept:'application/json'}}))}
async function subtaskType(projectId:string){const p=await json<{issueTypes?:Array<{id?:string;subtask?:boolean;name?:string}>}>(await api.asApp().requestJira(route`/rest/api/3/project/${projectId}`,{headers:{Accept:'application/json'}}));const t=(p.issueTypes||[]).find(x=>x.subtask)||(p.issueTypes||[]).find(x=>/sub.?task/i.test(x.name||''));if(!t?.id)throw new Error(`No sub-task type in project ${projectId}`);return String(t.id)}
function adf(text:string){return{type:'doc',version:1,content:text?[{type:'paragraph',content:[{type:'text',text}]}]:[]}}
function nodeLabel(node:GraphNode){return `ivanti-node-${node.id.replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,40)}`}
async function createTask(plan:ExecutableGraphPlan,state:State,node:GraphNode){if(state.createdTasks[node.id])return;const type=await subtaskType(plan.projectId);const desc=[node.details,node.team&&`Ivanti assignment team: ${node.team}`,node.dueDays&&`Ivanti due target: ${node.dueDays} day(s)`].filter(Boolean).join('\n\n');const made=await json<{key:string}>(await api.asApp().requestJira(route`/rest/api/3/issue`,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({fields:{project:{id:plan.projectId},parent:{key:state.parentIssueKey},issuetype:{id:type},summary:node.summary||node.title,description:adf(desc||`Migrated Ivanti fulfilment task: ${node.title}`),labels:['ivanti-orchestration',nodeLabel(node)]}})}));state.createdTasks[node.id]=made.key;await saveState(state)}
async function saveState(s:State){s.updatedAt=new Date().toISOString();await kvs.set(stateKey(s.parentIssueId),s)}
function outgoing(plan:ExecutableGraphPlan,id:string,outcome?:string){const edges=plan.transitions.filter(e=>e.sourceId===id);if(!outcome)return edges;const n=norm(outcome);return edges.filter(e=>{const o=norm(e.outcome);return o===n||(!o&&['ok','completed','true'].includes(n))})}
function addActive(state:State,ids:string[]){for(const id of ids)if(!state.active.includes(id)&&!state.passed.includes(id))state.active.push(id)}
async function fieldValue(parent:Issue,condition:string|undefined){if(!condition)return undefined;const m=condition.match(/^(.+?)\s+(equals|=|==|is|not equals|!=)\s+(.+)$/i);if(!m)return undefined;const fieldName=norm(m[1]);const expected=clean(m[3]).replace(/^['"]|['"]$/g,'');const fields=await json<Array<{id?:string;name?:string}>>(await api.asApp().requestJira(route`/rest/api/3/field`,{headers:{Accept:'application/json'}}));const f=fields.find(x=>norm(x.name)===fieldName)||fields.find(x=>norm(x.name).includes(fieldName)||fieldName.includes(norm(x.name)));if(!f?.id)return undefined;const actual=(await issue(parent.key)).fields?.[String(f.id)];const value=typeof actual==='object'&&actual&&'value'in actual?actual.value:actual;const eq=norm(value)===norm(expected);return /not|!=/i.test(m[2])?!eq:eq}
function taskOutcomeFromStatus(node:GraphNode,statusName:unknown,statusCategory:unknown){const status=norm(statusName);const cat=norm(statusCategory);const available=node.outcomes.map(norm);const aliases:Array<[string,string[]]>=[['accepted',['accepted','accept']],['completed',['completed','complete','done','resolved','closed']],['cancelled',['cancelled','canceled','cancel']],['canceled',['cancelled','canceled','cancel']],['timed out',['timed out','timeout','timedout']],['timeout',['timed out','timeout','timedout']],['failed',['failed','failure','rejected']],['ok',['ok','success']]];for(const [outcome,names] of aliases)if(available.includes(outcome)&&names.some(name=>status===norm(name)||status.includes(norm(name))))return outcome;if(cat==='done'){if(available.includes('completed'))return'completed';if(available.includes('ok'))return'ok';if(available.length===1)return available[0]}return undefined}
async function taskOutcome(state:State,node:GraphNode){const key=state.createdTasks[node.id];if(!key)return undefined;const child=await issue(key);return taskOutcomeFromStatus(node,child.fields?.status?.name,child.fields?.status?.statusCategory?.key)}
async function refreshTaskTruth(plan:ExecutableGraphPlan,state:State){let changed=false;for(const [nodeId,key] of Object.entries(state.createdTasks)){const node=plan.nodes.find(n=>n.id===nodeId);if(!node||node.kind!=='task'||!key)continue;const child=await issue(key);const outcome=taskOutcomeFromStatus(node,child.fields?.status?.name,child.fields?.status?.statusCategory?.key);if(!outcome)continue;if(state.active.includes(nodeId)){state.active=state.active.filter(x=>x!==nodeId);changed=true}if(!state.passed.includes(nodeId)){state.passed.push(nodeId);changed=true}const before=state.active.length;addActive(state,outgoing(plan,nodeId,outcome).map(e=>e.targetId));if(state.active.length!==before)changed=true}return changed}
async function transitionDone(key:string){const body=await json<{transitions?:Array<{id?:string;name?:string;to?:{name?:string;statusCategory?:{key?:string}}}>}>(await api.asApp().requestJira(route`/rest/api/3/issue/${key}/transitions`,{headers:{Accept:'application/json'}}));const t=(body.transitions||[]).find(x=>norm(x.to?.statusCategory?.key)==='done')||(body.transitions||[]).find(x=>/done|complete|resolve|close/i.test(x.to?.name||x.name||''));if(t?.id)await json(await api.asApp().requestJira(route`/rest/api/3/issue/${key}/transitions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transition:{id:String(t.id)}})}))}
function reached(state:State,nodeId:string){return state.passed.includes(nodeId)||state.active.includes(nodeId)||Boolean(state.createdTasks[nodeId])}
async function reconcile(plan:ExecutableGraphPlan,parent:Issue){let state=await kvs.get(stateKey(parent.id)) as State|undefined;if(!state){state={parentIssueId:String(parent.id),parentIssueKey:parent.key,createdTasks:{},active:[...plan.entryNodeIds],passed:[],completed:false,updatedAt:new Date().toISOString()};await saveState(state)}if(state.completed)return;let changed=true;let guard=0;while(changed&&guard++<100){changed=await refreshTaskTruth(plan,state);for(const id of [...state.active]){const node=plan.nodes.find(n=>n.id===id);if(!node){state.active=state.active.filter(x=>x!==id);changed=true;continue}if(node.kind==='unsupported'||node.kind==='approval'||node.kind==='wait')continue;if(node.kind==='task'){await createTask(plan,state,node);const outcome=await taskOutcome(state,node);if(!outcome)continue;state.active=state.active.filter(x=>x!==id);if(!state.passed.includes(id))state.passed.push(id);addActive(state,outgoing(plan,id,outcome).map(e=>e.targetId));changed=true;continue}if(node.kind==='gate'){const incoming=[...new Set(plan.transitions.filter(e=>e.targetId===id).map(e=>e.sourceId))];const participating=incoming.filter(src=>reached(state,src));if(!participating.length||participating.some(src=>!state.passed.includes(src)))continue;state.active=state.active.filter(x=>x!==id);if(!state.passed.includes(id))state.passed.push(id);addActive(state,outgoing(plan,id).map(e=>e.targetId));changed=true;continue}if(node.kind==='decision'){let selected:GraphTransition[]=[];for(const e of outgoing(plan,id)){const test=await fieldValue(parent,e.condition||node.condition);if(test===true){selected=[e];break}}if(!selected.length){const edges=outgoing(plan,id);const yes=edges.find(e=>['true','yes'].includes(norm(e.outcome)));const no=edges.find(e=>['false','no'].includes(norm(e.outcome)));const test=await fieldValue(parent,node.condition);if(test!==undefined)selected=[test?yes:no].filter(Boolean) as GraphTransition[]}if(!selected.length)continue;state.active=state.active.filter(x=>x!==id);if(!state.passed.includes(id))state.passed.push(id);addActive(state,selected.map(e=>e.targetId));changed=true;continue}if(node.kind==='stop'){state.active=state.active.filter(x=>x!==id);if(!state.passed.includes(id))state.passed.push(id);state.completed=true;await transitionDone(parent.key);changed=true;continue}if(node.kind==='start'||node.kind==='action'){state.active=state.active.filter(x=>x!==id);if(!state.passed.includes(id))state.passed.push(id);addActive(state,outgoing(plan,id).map(e=>e.targetId));changed=true;continue}}if(changed)await saveState(state)}await saveState(state)}
export async function saveExecutableGraph(raw:ExecutableGraphPlan){if(!raw?.projectId||!raw?.issueTypeId||!raw?.nodes?.length)throw new Error('Graph plan is missing project, issue type or nodes.');const ids=new Set(raw.nodes.map(n=>n.id));for(const e of raw.transitions)if(!ids.has(e.sourceId)||!ids.has(e.targetId))throw new Error(`Graph route references unknown node: ${e.sourceTitle} -> ${e.targetTitle}`);const plan={...raw,version:2 as const,installedAt:new Date().toISOString()};await kvs.set(planKey(plan.projectId,plan.issueTypeId),plan);return plan}
export async function getExecutableGraph(projectId:string,issueTypeId:string){return await kvs.get(planKey(projectId,issueTypeId)) as ExecutableGraphPlan|undefined}
export async function getGraphState(issueId:string){return await kvs.get(stateKey(issueId)) as State|undefined}
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

/** Jira may deliver sibling subtask updates concurrently. Each reconciliation re-derives completed
 * task truth from Jira itself before evaluating gates, so stale KVS writes cannot permanently lose
 * a sibling completion. Join gates only wait for predecessors that actually participated in this run;
 * unreachable Ivanti branches must not deadlock the active path. */
export async function handleGraphIssueEvent(event:any){const raw=event?.issue;if(!raw?.id)return;const eventType=norm(event?.eventType||event?.type||'');const current=await issue(raw.key||raw.id);const isSubtask=Boolean(current.fields?.issuetype?.subtask);const isCreated=eventType.includes('created');const isUpdated=eventType.includes('updated');if(isSubtask){const labels=current.fields?.labels||[];if(!labels.includes('ivanti-orchestration'))return;if(isCreated)return;if(!isUpdated)return}else{if(!isCreated)return}let parent=current;if(isSubtask&&current.fields?.parent?.key)parent=await issue(current.fields.parent.key);const projectId=String(parent.fields?.project?.id||'');const typeId=String(parent.fields?.issuetype?.id||'');if(!projectId||!typeId)return;const plan=await getExecutableGraph(projectId,typeId);if(!plan)return;const createdAt=Date.parse(String(parent.fields?.created||''));const installedAt=Date.parse(String(plan.installedAt||''));if(Number.isFinite(createdAt)&&Number.isFinite(installedAt)&&createdAt<installedAt)return;await reconcile(plan,parent);if(isSubtask){await sleep(3000);const freshParent=await issue(parent.key);await reconcile(plan,freshParent)}}